### ISSUE TITLE
Null "hardware ID"

### ISSUE THREAD

**Issue by JesseFST** [RobertoGraham/fortnite-2#11]
Hi, am receiving a null value when trying to receive the Hardware ID of the network interface.
The server's network adapter works just fine, it makes a connection to the Internet and all.
The server runs as a VMWare virtual machine, running Ubuntu Linux 16.04.6 LTS.

While running `ifconfig`, I can see the network adapter returns the `HWaddr` without any issues.

`Exception in thread "main" java.lang.NullPointerException
	at io.github.robertograham.fortnite2.implementation.DefaultFortnite.<init>(DefaultFortnite.java:52)
	at io.github.robertograham.fortnite2.implementation.DefaultFortnite$Builder.build(DefaultFortnite.java:331)
`

Please look into this.

**Comment by RobertoGraham** [comment]
Yes I will take a look, in the meantime consider using the Builder method `setDeviceId` to provide your own
